version: '3.7'
services:
  server:
    build: .
    image: server_node_cicd
    container_name: node_cicd
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
    volumes:
      - './:/usr/app'